@host=http://localhost:5071
@adminId=a3f8c7b2-51e9-4d6a-8c42-7f1b95d0e3a1

POST {{host}}/Tasks
Content-Type: application/json

  
  "userId": "{{adminId}}",
  "title": "New Task",
  "description": "This is a new task.",
  "dueDate": "2024-12-31T23:59:59Z",
  "priority": "High",
  "status": "Open"    
